name: Run Bot

on:
  schedule:
    - cron: '0 0 * * *'  # 9 โมงไทย
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install
      - run: npx playwright install chromium

      - name: Run bot
        run: node index.js
        env:
        SHEET_URL: ${{ secrets.SHEET_URL }}
        JOBBKK_USER: ${{ secrets.JOBBKK_USER }}
        JOBBKK_PASS: ${{ secrets.JOBBKK_PASS }}
        WEB: ${{ secrets.WEB }}
        PAGE: ${{ secrets.PAGE }}
        API_KEY: ${{ secrets.API_KEY }}